export { default as Contact } from './Contact'
export { default as Contribute } from './Contribute'
export { default as CourseFinder } from './CourseFinder'
export { default as Favourites } from './Favourites'
export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Logout } from './Logout'
export { default as NotFound } from './NotFound'
export { default as CoursePage } from './CoursePage'
export { default as Settings } from './Settings'
export {default as MinorDepartments} from './MinorDepartments'
export {default as MinorDepartmentPage } from './MinorDepartmentPage'
export {default as HonorsDepartments} from './HonorsDepartments'
export {default as HonorsDepartmentPage } from './HonorsDepartmentPage'